/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TracksImport } from './routes/tracks'

// Create/Update Routes

const TracksRoute = TracksImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/tracks': typeof TracksRoute
}

export interface FileRoutesByTo {
  '/tracks': typeof TracksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/tracks': typeof TracksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tracks'
  fileRoutesByTo: FileRoutesByTo
  to: '/tracks'
  id: '__root__' | '/tracks'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  TracksRoute: typeof TracksRoute
}

const rootRouteChildren: RootRouteChildren = {
  TracksRoute: TracksRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/tracks"
      ]
    },
    "/tracks": {
      "filePath": "tracks.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
